export const profile = {
  name: '윤우중',
  role: '웹 개발자',
  tagline: '서비스의 흐름을 이해하고, 끝까지 구현하는 웹 개발자.',
  intro:
    '프론트엔드의 사용자 경험부터 백엔드 기능과 운영 환경까지 폭넓게 고민합니다. React와 TypeScript를 중심으로 웹 서비스를 만들며, AI 도구를 개발 과정에 활용해 구현과 검증의 생산성을 높이고 배포 이후의 개선까지 책임집니다.',
  email: 'ywj98121791@gmail.com',
  phone: '010-4163-7540',
  location: '경기도 화성시 동탄구',
  birth: '1998년생 (만 27세)',
  availability: 'twentyoz 재직 중 · 주임 웹개발자',
  valuePoints: [
    { label: 'Development', value: 'Frontend · Backend' },
    { label: 'Domain', value: 'EMS · Web SaaS' },
    { label: 'Delivery', value: 'Docker · 배포 · 운영' },
  ],
  portfolio: 'https://developing-cell-df2.notion.site/1a1047c27d53806a9919fddc2791366f',
  links: [
    { label: 'GitHub', href: 'https://github.com/woojoung1217' },
    { label: 'Portfolio', href: 'https://developing-cell-df2.notion.site/1a1047c27d53806a9919fddc2791366f' },
    { label: 'Email', href: 'mailto:ywj98121791@gmail.com' },
  ],
  metrics: [
    { value: 'Web', label: 'Frontend & Backend' },
    { value: '3', label: 'SaaS Products' },
    { value: '1st', label: '장관상 수상' },
  ],
  facts: [
    { label: '현재', value: 'twentyoz 웹개발팀 주임' },
    { label: '학력', value: '순천향대학교 컴퓨터소프트웨어 졸업' },
    { label: '희망 직무', value: '웹 개발자 · 프론트엔드 개발자' },
    { label: '병역', value: '육군 병장 만기 제대' },
  ],
  experience: [
    {
      period: '2026. 03 — 재직 중',
      company: 'twentyoz (트웬티온즈)',
      role: '웹개발팀 · 주임 웹개발자',
      summary: '태양광 EMS 서비스 풀스택 개발 및 현장 엔지니어링',
      bullets: [
        '태양광 발전소의 발전량·설비 상태·알람을 확인하는 EMS 모니터링 화면과 운영 기능을 프론트엔드부터 백엔드까지 개발',
        'P&ID 계통도와 인버터·접속반 등 설비별 상세 화면을 작화하고, 실시간 태그 데이터가 화면에 정확히 표현되도록 연동·검증',
        'InfoU 기반 설비 데이터 구조를 분석해 태그를 매핑하고 Modbus 주소, 데이터 타입, 스케일 등 통신 정보를 관리',
        '고객사 내부망 환경에 운영 서버를 배포하고 서버·클라이언트 간 접속, 설비 통신, 서비스 구동 상태를 점검',
        '현장 엔지니어링 과정에서 계통도·태그 목록과 실제 설비 데이터를 대조하고 오표기·통신 누락 사항을 수정',
        '고객 요구사항을 운영 화면과 기능에 반영하고 배포 이후 데이터·화면 이상 여부를 확인하며 서비스 안정화 지원',
        'Twentyoz Tech Blog의 공개 웹·Admin·백엔드 기능을 개발하고 운영 환경에 배포',
        '세기P&C 통합 온라인 플랫폼 세기몰의 PC·모바일 UI 구축 및 운영 유지보수',
      ],
      tags: ['React', 'TypeScript', 'JavaScript', 'NestJS', 'MySQL', 'EMS', 'InfoU', 'Modbus', 'Internal Network', 'GitLab'],
      projects: [
        {
          title: '영암 태양광·ESS EMS',
          type: '에너지 관리 시스템 고도화 · 풀스택 개발 및 릴리즈 엔지니어링',
          description: '태양광 발전 설비와 ESS의 발전·충방전 현황, 계통 상태, 설비 알람 및 운전 이력을 통합 모니터링하는 EMS입니다. 기존 운영 시스템의 데이터와 화면 동작을 분석해 React·NestJS 기반 서비스로 고도화하고, 내부망 설치를 위한 배포 체계까지 구축했습니다.',
          contributions: [
            'React 기반 메인 대시보드에 GIS·PV·ESS 전력, 일사량과 SOC 실시간 시계열을 통합하고 ECharts 다축 차트·확대·다운로드 기능 구현',
            '태양광·ESS 운전 현황 화면의 일별 캘린더, 발전량 요약과 설비별 시계열 조회 UI 개발',
            'NestJS 백엔드에 EMS 상태 조회 API와 1분 주기 데이터 수집 Worker를 구현하고 분 단위 스냅샷을 누적 저장',
            'Drizzle ORM 기반 스키마와 Repository를 구성해 SQLite·PostgreSQL 환경에서 동일한 상태 이력 기능 지원',
            'XD Runtime의 설비·태그·Historian 데이터를 연동하고 개발 환경에서도 운영 Runtime을 안전하게 조회할 수 있도록 요청 경로와 프로젝트 헤더 처리 구성',
            '2D 계통도와 설비 상세 모달을 연결하고 선택한 설비의 태그 그룹을 동적으로 바인딩하는 Runtime Function 구조 구현',
            'HV 계측·보호·통신 상태와 PV 접속반 알람을 실제 태그 구조에 맞춰 작화하고 결측·통신 오류 시 오래된 값을 정상값처럼 표시하지 않도록 안전 처리',
            'PV 발전량과 ESS 충·방전량의 일·주·월·년 파생 태그 및 기간 기준값 로직을 설계하고 등록·검증 자동화 스크립트 작성',
            'Docker 멀티 스테이지 빌드와 GitLab CI를 구성해 이미지 빌드·레지스트리 릴리즈·헬스 체크 기반 배포 자동화',
            '외부 인터넷이 제한된 Windows 내부망 설치를 위해 UI·API·Node Runtime을 묶은 번들과 NSIS 설치 프로그램, NSSM 서비스 등록 및 기동 검증 절차 구성',
          ],
          technicalNotes: [
            { label: '실시간 데이터 파이프라인', value: 'XD Runtime 계측값을 분 단위로 수집·저장하고 조회 기간에 맞게 집계해 대시보드와 운전 현황 차트에 전달' },
            { label: '산업 데이터 신뢰성', value: '구 시스템 정의, 계통도, 태그 목록과 실제 Runtime 값을 대조하고 null·비수치·통신 오류를 구분해 잘못된 정상 상태 표시 방지' },
            { label: '동적 설비 화면', value: '공통 2D 도면에 선택 설비의 태그 그룹과 페이지 파라미터를 주입해 여러 설비 상세 화면에서 재사용' },
            { label: '내부망 릴리즈', value: 'Docker와 Windows 설치형 배포를 모두 지원하고 환경 설정, 데이터 영속화, 서비스 자동 재시작과 API Health Check로 설치 안정성 확보' },
          ],
          stack: ['React 19', 'TypeScript', 'TanStack Query', 'TanStack Router', 'ECharts', 'Ant Design', 'Panda CSS', 'NestJS', 'Drizzle ORM', 'SQLite', 'PostgreSQL', 'Docker', 'GitLab CI', 'Bun', 'Turbo', 'XD Runtime', 'NSIS', 'NSSM'],
        },
        {
          title: '홋카이도 태양광 EMS',
          type: 'LS ELECTRIC 협력 프로젝트 · 풀스택 개발 및 현장 엔지니어링',
          description: 'LS ELECTRIC이 수행하는 일본 홋카이도 태양광 발전소 프로젝트의 EMS 구축 업무로, 발전량과 설비 상태, 알람, 전력 계통 흐름을 통합 모니터링하고 운영하기 위한 서비스입니다.',
          contributions: [
            'EMS 대시보드와 설비 모니터링·운영 화면의 프론트엔드 및 관련 백엔드 기능 개발',
            '단선결선도와 P&ID를 바탕으로 인버터·접속반·전력 계측 설비의 계통도 및 상세 화면 작화',
            'InfoU 태그를 화면 컴포넌트에 매핑하고 Modbus 주소·데이터 타입·스케일·읽기 값을 대조해 데이터 정확성 검증',
            '외부 인터넷 접속이 제한된 고객사 내부망 환경에서 서버와 클라이언트를 구성하고 운영 서비스 배포',
            'Docker 기반으로 애플리케이션 이미지를 빌드·릴리즈하고 내부망 서버에 컨테이너 배포',
            '배포 후 컨테이너 실행 상태와 로그, 환경 변수 및 서비스 포트를 확인해 구동 오류 점검',
            '내부망 IP·포트와 서버 프로세스, 클라이언트 접속, 설비 통신 및 실시간 데이터 수신 상태 점검',
            '화면 표시 값과 태그 목록, 실제 설비 데이터를 교차 검증하고 오표기·통신 누락·이상 데이터를 수정',
            '고객 요구사항과 현장 피드백을 기능 및 화면에 반영하고 배포 이후 안정화 지원',
          ],
          technicalNotes: [
            { label: '데이터 신뢰성', value: '태그 정의서·Modbus 정보·실제 수신 값·화면 표시 값을 교차 검증해 데이터 불일치 원인을 추적' },
            { label: 'Docker 릴리즈', value: '애플리케이션 이미지를 빌드해 내부망 서버에 전달·배포하고 컨테이너 상태, 로그, 환경 변수와 포트를 단계별 점검' },
          ],
          stack: ['React', 'TypeScript', 'NestJS', 'MySQL', 'Docker', 'InfoU', 'Modbus TCP', 'P&ID', 'Internal Network', 'Linux', 'GitLab'],
        },
        {
          title: 'Twentyoz Tech Blog',
          type: '기업 기술 블로그 · 풀스택 개발 및 운영 배포',
          url: 'https://blog.twentyoz.app/',
          description: '트웬티온스의 기술 아티클과 실무 인사이트를 발행하는 기업 기술 블로그입니다. 공개 웹과 콘텐츠 관리 Admin, API를 함께 개발하고 실제 서비스 환경에 배포했습니다.',
          contributions: [
            '아티클 목록·상세, 검색, 태그 탐색과 세션 콘텐츠 등 공개 블로그 화면 개발 및 개선',
            '한국어·영어 콘텐츠 경로와 테마 전환을 지원하고 반응형 사용자 경험 정비',
            '페이지별 메타데이터, Open Graph, 구조화 데이터, canonical·hreflang과 RSS를 적용해 검색 및 콘텐츠 공유 환경 구성',
            'Admin에서 게시글·카테고리·태그·작성자·이미지 업로드와 게시 상태를 관리하는 기능 개발',
            'NestJS와 Prisma 기반 콘텐츠 API 및 데이터 모델을 구성하고 프론트엔드와 연동',
            'Docker 기반 릴리즈를 통해 운영 도메인에 공개 웹과 Admin·API를 배포하고 환경 설정과 서비스 응답 상태 점검',
            '배포 이후 콘텐츠 노출, 이미지, 검색과 다국어 경로 등의 운영 이슈를 확인하고 지속적으로 개선',
          ],
          technicalNotes: [
            { label: '풀스택 구조', value: '공개 웹·Admin·API를 분리하고 React와 NestJS·Prisma 기반으로 콘텐츠 생성부터 노출까지의 흐름 구현' },
            { label: '검색·배포 품질', value: 'SSR 메타데이터, 구조화 데이터, RSS와 다국어 URL을 구성하고 운영 도메인 배포 후 응답과 노출 상태 검증' },
          ],
          stack: ['React', 'TypeScript', 'TanStack Query', 'Ant Design', 'NestJS', 'Prisma', 'MySQL', 'Docker', 'SSR', 'SEO', 'RSS', 'GitLab'],
        },
        {
          title: '세기몰 (SAEKI)',
          type: '세기P&C 이커머스 · 라이브 서비스 운영',
          url: 'https://www.saeki.co.kr/',
          description: '카메라·렌즈·촬영 장비 판매와 브랜드 콘텐츠, 이벤트, 정품등록 및 매장 안내를 제공하는 세기P&C의 실제 운영 중인 통합 온라인 플랫폼입니다. PC·모바일 신규 화면 구축과 운영 UI 유지보수를 담당했습니다.',
          contributions: [
            'PC·모바일 매장 안내 및 상세 페이지를 신규 구축하고 브랜드·상품 탐색 인터랙션 구현',
            '상품 필터와 예약판매·배송 안내, GNB 메가 메뉴 등 주요 쇼핑 UI 개선',
            '이벤트·전시·고객지원·정품등록·정책 페이지를 PC·모바일 환경에 제작 및 적용',
            '백오피스 에디터 콘텐츠의 스타일 충돌과 주문결제·슬라이더·레이아웃 오류 해결',
            '운영 요청을 반영하며 PC·모바일 간 UI 일관성과 콘텐츠 가독성 지속 개선',
          ],
          technicalNotes: [
            { label: '라이브 서비스 유지보수', value: '기존 jQuery 구조와 구매 흐름의 영향을 확인하며 기능을 추가하고 운영 중 발생한 UI 회귀와 노출 오류를 수정' },
            { label: 'PC·모바일 이원화 대응', value: '별도 마크업으로 운영되는 두 환경의 기능과 콘텐츠를 맞추고 백오피스 HTML의 스타일 충돌을 보정' },
          ],
          stack: ['HTML5', 'CSS3', 'JavaScript', 'jQuery', 'Swiper', 'Git', 'GitLab'],
        },
      ],
      current: true,
    },
    {
      period: '2025. 06 — 2025. 09',
      company: '포그리트',
      role: '플랫폼개발팀 · 웹 개발자',
      summary: '웹 분석 SaaS와 사내 CRM의 프론트엔드 개발 및 유지보수',
      bullets: [
        'BAX: Vue 3 Composition API 기반 진단 UI를 개발하고, 접근성 위반 위치를 캡처 이미지와 HTML 코드 트리에서 동시에 확인하도록 상태를 연동',
        'BAX: Vue i18n으로 한국어·영어·일본어를 지원하고 TanStack Query 캐싱을 적용해 중복 API 요청과 서버 상태 관리 복잡도를 개선',
        'Eagle M: 고객·연락처·회원·권한, 견적 생성 및 결제 내역 관리 기능을 고도화하고 html2pdf 기반 PDF 견적서 자동 생성 구현',
        'Eagle M: 반복 UI를 공통 컴포넌트로 정리하고 TypeScript 타입을 보강해 변경 영향 범위와 유지보수 비용을 축소',
        'Beusable: 스크롤 리포트 데이터를 Canvas와 Chart.js로 시각화하고 서비스 요구사항에 맞게 차트 렌더링을 커스터마이징',
        'Beusable: 배포 이후 유지보수와 Jira 기반 QA에 참여해 재현 조건 확인, 이슈 수정 및 회귀 점검 수행',
      ],
      tags: ['Vue 3', 'Composition API', 'TypeScript', 'Vue i18n', 'TanStack Query', 'Canvas', 'Chart.js', 'html2pdf', 'Jira'],
      projects: [
        {
          title: 'BAX',
          type: '웹 접근성 자동 진단 SaaS · 프론트엔드 개발',
          description: '사용자가 URL을 입력하면 Puppeteer 기반 크롤링 결과를 WCAG 기준으로 분석하고, 접근성 위반 항목과 실제 발생 위치를 시각적으로 제공하는 서비스입니다.',
          contributions: [
            'Vue 3 Composition API와 TypeScript 기반으로 진단 결과, 위반 항목 상세 및 필터 UI 개발',
            '위반 요소 선택 시 캡처 이미지의 좌표와 HTML 코드 트리 노드를 함께 활성화하는 양방향 탐색 흐름 구현',
            '캡처 화면과 코드 트리에서 문제 위치를 바로 비교하도록 개선해 위반 지점 확인 소요 시간 약 40% 단축',
            'Vue i18n 기반 한국어·영어·일본어 다국어 리소스와 화면 전환 기능 구현',
            '회원가입·로그인, 이메일 인증과 인증 상태에 따른 접근 제어 UI 구현',
            'Vue TanStack Query의 query key와 캐시 정책을 정리해 불필요한 API 호출량 약 25% 감소 및 로딩 경험 개선',
          ],
          technicalNotes: [
            { label: '복합 뷰 동기화', value: '위반 항목 ID를 기준으로 진단 목록, 캡처 좌표와 HTML 노드 상태를 연결해 서로 다른 표현에서도 동일한 문제를 추적' },
            { label: '비동기 상태 최적화', value: '진단 결과와 상세 조회의 query key·stale 상태를 구분하고 로딩·오류 처리를 공통화해 중복 요청과 화면 분기 축소' },
            { label: '접근성 도메인 UI', value: 'WCAG 위반 기준과 영향도를 사용자가 이해할 수 있도록 계층화하고 코드·화면 근거를 함께 제공' },
          ],
          stack: ['Vue 3', 'Composition API', 'TypeScript', 'TanStack Query', 'Vue i18n', 'Puppeteer Result', 'WCAG', 'Web Accessibility'],
        },
        {
          title: 'Eagle M',
          type: '고객·견적·결제 관리 CRM',
          description: '고객과 연락처, 회원 권한, 견적 및 결제 내역을 통합 관리하는 사내 시스템입니다.',
          contributions: [
            '고객·회원·권한 관리와 견적·결제 확인 기능 고도화',
            '서비스별 가격과 산정 내역을 PDF 견적서로 자동 생성해 평균 작성 시간을 15분에서 1분 이내로 단축',
            '공통 UI 컴포넌트 정리와 TypeScript 타입 안정성 강화',
          ],
          technicalNotes: [
            { label: '업무 자동화', value: '서비스별 가격과 산정 데이터를 문서 구조로 변환해 반복적인 견적서 작성 과정을 PDF 생성 기능으로 자동화' },
          ],
          stack: ['Vue', 'TypeScript', 'html2pdf', 'Component Design'],
        },
        {
          title: 'Beusable',
          type: '웹사이트 UX 분석 SaaS',
          description: '사용자의 클릭, 스크롤과 이동 경로를 분석해 히트맵 및 행동 리포트를 제공하는 서비스입니다.',
          contributions: [
            '스크롤 리포트 데이터를 Canvas와 Chart.js 기반 맞춤형 차트로 시각화',
            '배포 이후 유지보수와 Jira 기반 QA, 이슈 수정 및 회귀 점검',
          ],
          technicalNotes: [
            { label: '데이터 시각화', value: '스크롤 데이터를 서비스 지표에 맞게 가공하고 Canvas·Chart.js 렌더링을 커스터마이징해 리포트로 표현' },
          ],
          stack: ['Vue', 'TypeScript', 'Canvas', 'Chart.js', 'Jira'],
        },
      ],
    },
  ],
  personalProjects: [
    {
      period: '2024. 10 — 2025. 05',
      title: 'TOUCHEESE',
      subtitle: '사진관 검색·예약 중개 플랫폼',
      description: '취향에 맞는 스튜디오를 탐색하고 예약과 촬영 정보를 관리할 수 있는 반응형 웹 서비스입니다.',
      contributions: [
        'React Helmet 메타 태그, 시맨틱 마크업, robots.txt와 sitemap.xml을 적용해 SPA 검색 노출 환경 개선',
        '매장 옵션·가격 필터 선택을 URL 쿼리 파라미터와 전역 상태에 동기화하는 커스텀 Hook 설계',
        '정규표현식 기반 동적 입력 검증 NPM 라이브러리를 제작·배포해 프로젝트의 검증 규칙을 일관되게 적용',
        'AWS S3와 CloudFront로 이미지 콘텐츠를 제공하고 GitHub Actions 기반 배포 자동화 구성',
        'Vitest로 사용자 입력과 렌더링을 검증하는 UI 컴포넌트 단위 테스트 작성',
      ],
      outcomes: ['NPM 다운로드 180+회', '반응형 웹', 'CI/CD 자동화'],
      stack: ['React', 'TypeScript', 'Zustand', 'TanStack Query', 'Emotion', 'Vitest', 'AWS S3', 'CloudFront', 'GitHub Actions'],
    },
    {
      period: '2024. 07 — 2024. 09',
      title: 'Highlightalk',
      subtitle: '메신저 대화 내용 AI 분석 서비스',
      description: 'CSV·TXT 메신저 대화를 구조화하고 GPT-4o mini로 분석해 관계와 대화 지표를 시각화하는 서비스입니다.',
      contributions: [
        '파일 형식에 맞춰 대화 내용을 파싱하고 분석 가능한 JSON 데이터로 변환하는 업로드 흐름 구현',
        '정규표현식 전처리로 불필요한 대화를 제거해 평균 입력 토큰을 19,000+개에서 5,700+개로 70% 이상 절감',
        'JSON 기반 프롬프트와 응답 구조를 적용해 분석 결과의 형식과 처리 흐름을 일관되게 구성',
        'Dynamic Import와 캐싱 전략으로 불필요한 렌더링을 줄여 Lighthouse 성능 점수를 55에서 89로 개선',
        '분석 결과와 커뮤니티 페이지 UI 및 Chart.js·D3 기반 데이터 시각화 구현',
      ],
      outcomes: ['입력 토큰 70%+ 절감', 'Lighthouse 55 → 89', 'AI 분석 파이프라인'],
      stack: ['Next.js', 'TypeScript', 'GPT-4o mini', 'Zustand', 'Chart.js', 'D3', 'SCSS', 'AWS EC2', 'Vercel'],
    },
    {
      period: '2024. 09 — 2024. 11',
      title: 'WISH',
      subtitle: '난임 부부를 위한 AI 심리 상담·케어 서비스',
      description: '난임 및 우울증 상담센터의 접근성을 높이기 위해 AI 기반 상담과 심리 지표 시각화를 모바일 환경으로 구현한 서비스입니다.',
      contributions: [
        '요구사항 분석, 사용자 흐름과 ERD 설계를 통해 서비스 기능 및 데이터 관계 정의',
        '쿼리스트링 기반 회원가입을 Funnel 구조와 커스텀 Hook으로 개선해 가입 시간을 약 20초에서 10초로 단축',
        'API 응답 타입을 명확히 정의해 상담 데이터 처리의 안정성과 코드 가독성 개선',
        '5개 주요 심리 지표를 레이더·캔들 차트로 시각화하고 사용자 맞춤 결과 화면 구현',
      ],
      outcomes: ['고용노동부 장관상', '가입 시간 50% 단축', 'AI 상담 경험 설계'],
      stack: ['React', 'TypeScript', 'OpenAI API', 'Zustand', 'Emotion', 'Chart.js'],
    },
  ],
  activities: [
    {
      period: '2024. 10 — 2025. 01',
      title: '멋쟁이사자처럼 인턴',
      description: 'React와 TypeScript 기반 스튜디오 검색·예약 UI와 촬영 일정 관리 기능을 개발했습니다. 기획과 디자인부터 참여해 사용자 흐름을 설계하고, Jira 기반 협업과 UI 단위 테스트를 통해 사용성과 안정성을 개선했습니다.',
    },
    {
      period: '2023. 12 — 2024. 04',
      title: '테킷 프론트엔드 스쿨',
      description: '페이지 개발, 공통 컴포넌트, API 연동, 상태 관리, SSR, 무한 스크롤, 데이터 시각화와 배포·운영까지 실무 중심의 프론트엔드 과정을 수료했습니다.',
    },
    {
      period: '심화 과정',
      title: '멋쟁이사자처럼 프론트엔드 심화',
      description: 'Next.js 기반 AI 분석 서비스를 팀으로 개발하며 파일 업로드, GPT 결과 생성, 데이터 시각화, 위치 기반 기능과 성능 최적화를 구현했습니다.',
    },
    {
      period: '2023. 12 — 2024. 05',
      title: 'JavaScript 스터디 타닥타닥 · 팀장',
      description: '6명 규모의 스터디를 운영하며 주 3회 학습 내용을 발표하고 Context, Closure, Event Loop 등 JavaScript 핵심 원리를 실습 예제와 함께 탐구했습니다.',
    },
  ],
  award: {
    year: '2024',
    title: '고용노동부 장관상',
    event: '제6회 K-디지털 트레이닝 해커톤',
    description: '저출산·고령사회 문제 해결을 위한 AI 기반 심리 케어 서비스를 개발했습니다. 난임 및 우울증 상담센터를 모바일로 전환하고 서비스 구조와 핵심 기능 개발을 주도해 기술적 완성도와 사회적 가치를 인정받았습니다.',
  },
  education: {
    period: '2017. 03 — 2023. 03',
    school: '순천향대학교',
    major: '컴퓨터소프트웨어 · 4년제 졸업',
  },
  skills: ['React', 'TypeScript', 'JavaScript', 'Vue.js', 'Next.js', 'NestJS', 'HTML5', 'CSS', 'MySQL', 'PostgreSQL', 'SQLite', 'Drizzle ORM', 'Docker', 'Linux', 'Git', 'GitLab'],
  aiUsage: [
    {
      title: '기능 구현 및 문제 해결',
      description: '요구사항을 작업 단위로 구체화하고 구현 방향, API 구조와 예외 처리 방안을 탐색할 때 AI를 활용합니다. 생성 코드는 프로젝트 구조와 팀 규칙에 맞게 직접 검토·수정합니다.',
    },
    {
      title: '테스트 및 코드 품질',
      description: '테스트 케이스와 경계 조건을 확장하고 반복 코드의 리팩터링 대안을 비교합니다. 타입, 실행 결과와 기존 기능의 회귀 여부는 로컬 빌드와 직접 테스트로 검증합니다.',
    },
    {
      title: '엔지니어링 데이터 정리',
      description: 'EMS 태그 목록, 설비 명칭과 작업 문서를 구조화하고 누락 가능성을 검토하는 보조 도구로 사용합니다. 설비 값과 통신 정보는 원본 문서 및 실제 수신 데이터와 대조해 확정합니다.',
    },
    {
      title: '문서화 및 지식 공유',
      description: '장애 원인, 배포 절차와 작업 이력을 이해하기 쉬운 형태로 초안화합니다. 보안이 필요한 내부망 정보와 고객 데이터는 입력하지 않고 비식별화된 맥락에서 활용합니다.',
    },
    {
      title: 'AI 서비스 개발 경험',
      description: 'Next.js 기반 프로젝트에서 GPT 분석 결과 생성, 파일 업로드와 결과 시각화 기능을 구현했으며 AI 심리 케어 서비스의 구조 및 핵심 기능 개발을 주도했습니다.',
    },
  ],
  introduction:
    '저는 프론트엔드와 백엔드 개발, Docker 기반 릴리즈와 운영까지 서비스의 전체 흐름을 책임지는 웹 개발자입니다. 태양광 EMS를 개발하며 웹 화면과 API뿐 아니라 설비 데이터 연동, 내부망 배포와 현장 엔지니어링을 경험했고, 기업 기술 블로그와 SaaS 제품을 개발하며 사용자 경험과 운영 안정성을 함께 고민해 왔습니다. 개발 과정에서는 AI를 요구사항 분석, 구현 방향 탐색, 테스트 케이스 확장과 문서화에 적극 활용합니다. 다만 생성된 결과를 그대로 적용하지 않고 프로젝트 구조, 타입, 보안과 실제 실행 결과를 직접 검증하며 품질을 책임집니다. 특히 고객 데이터와 내부망 정보는 AI에 입력하지 않는 원칙을 지키고 있습니다. 빠르게 변화하는 기술을 목적에 맞게 선택하고, 팀과 맥락을 공유하며, 개발부터 배포 이후의 개선까지 끝까지 완수하는 개발자가 되겠습니다.',
};
